# Generated by Django 5.0 on 2025-01-09 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Réponse', 'verbose_name_plural': 'Réponses'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Programme', 'verbose_name_plural': 'Programmes'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Sujet', 'verbose_name_plural': 'Sujets'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='documentation_text',
            field=models.TextField(blank=True, default='', verbose_name='texte de documentation'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='documentation_url',
            field=models.URLField(blank=True, default='', verbose_name='URL de documentation'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='decision_tree.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='texte'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AlterField(
            model_name='program',
            name='version',
            field=models.CharField(max_length=50, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='decision_tree.subject', verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='texte'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_subjects', to='decision_tree.subject', verbose_name='sujet parent'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='decision_tree.program', verbose_name='programme'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
    ]
